## .py: python script file
## .ipynb: interactive python notebook

In [ ]:
print("hello world")

hello world


## control statements

In [ ]:
a=5
if(a==0):
  print('zero')
elif(a%2==0):
  print('even')
else:
  print('odd')

odd


## looping statements: for, while, repeat

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5,10):
  print(i)

5
6
7
8
9


## data declaration

In [ ]:
import numpy as np #numerical python computation

declare the matrix 2x2

In [ ]:
a=np.array([[1,2],[3,4,]])

In [ ]:
print(a)

[[1 2]
 [3 4]]


changing dimension of matrix

In [ ]:
a=np.array([1,2,3,4,5],ndmin=3)

In [ ]:
print(a)

[[[1 2 3 4 5]]]


declare complex datatype: a+bj

In [ ]:
np.array([1,2,3,4,5],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

## series

In [ ]:
data = np.array(['a','b','c','d','e'])

In [ ]:
data

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [ ]:
import pandas as pd

In [ ]:
pd.Series(data)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
data={'Cricketer':['Dhoni','Sachin','Virat','Rohit'],'Scores':[75,71,60,51]}
pd.DataFrame(data)

Cricketer  Scores
0     Dhoni      75
1    Sachin      71
2     Virat      60
3     Rohit      51

randomization: declaration pf random values

In [ ]:
np.random.randn(3,2) #(no. of rows, no. of columns)

array([[ 0.61279449,  1.25269148],
       [ 1.59364511,  1.92341146],
       [-1.29869449, -0.39455783]])

In [ ]:
data=pd.DataFrame(np.random.randn(3,2))

In [ ]:
data

0         1
0  0.737943 -0.827440
1 -0.434427  1.101163
2  0.668908 -1.353104

In [ ]:
data=pd.DataFrame(np.random.randn(3,2),index=['a','c','d'],columns=['one','two'])

In [ ]:
data

one       two
a -0.476786 -0.597283
c -1.153120  0.845792
d -0.389572  0.915165

## data cleaning process

In [ ]:
data=data.reindex(['a','b','c','d','e','f'])

In [ ]:
data

one       two
a -0.476786 -0.597283
b       NaN       NaN
c -1.153120  0.845792
d -0.389572  0.915165
e       NaN       NaN
f       NaN       NaN

checking if ther are null values

In [ ]:
data.isnull()

one    two
a  False  False
b   True   True
c  False  False
d  False  False
e   True   True
f   True   True

dropping null values

In [ ]:
data.dropna()

one       two
a -0.476786 -0.597283
c -1.153120  0.845792
d -0.389572  0.915165

In [ ]:
data

one       two
a -0.476786 -0.597283
b       NaN       NaN
c -1.153120  0.845792
d -0.389572  0.915165
e       NaN       NaN
f       NaN       NaN

fill the missing values with mean

In [ ]:
data.fillna(data.mean())

one       two
a -0.476786 -0.597283
b -0.673159  0.387891
c -1.153120  0.845792
d -0.389572  0.915165
e -0.673159  0.387891
f -0.673159  0.387891

In [ ]:
data

one       two
a -0.476786 -0.597283
b       NaN       NaN
c -1.153120  0.845792
d -0.389572  0.915165
e       NaN       NaN
f       NaN       NaN

fill the values with reference to previous row

In [ ]:
data.fillna(method='pad')

one       two
a -0.476786 -0.597283
b -0.476786 -0.597283
c -1.153120  0.845792
d -0.389572  0.915165
e -0.389572  0.915165
f -0.389572  0.915165

In [ ]:
data.describe()

one       two
count  3.000000  3.000000
mean  -0.673159  0.387891
std    0.417939  0.853891
min   -1.153120 -0.597283
25%   -0.814953  0.124255
50%   -0.476786  0.845792
75%   -0.433179  0.880479
max   -0.389572  0.915165