In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math as math
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
#load dataset
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
col_names=["sepal length","sepal width","petal length","petal width","class"]
dataset=pd.read_csv(url,names=col_names)

In [3]:
dataset

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
dataset.shape

(150, 5)

In [41]:
training=dataset.values[:,0:4]
training

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
trainingclass=dataset.values[:,-1]
trainingclass

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
def euclidean_distance(A,B):
  distance=0
  for i in range(len(A)):
    distance+=(A[i]-B[i])**2
  distance=math.sqrt(distance)
  return distance

In [8]:
unique_class=list(set(trainingclass))

In [9]:
unique_class

['Iris-setosa', 'Iris-virginica', 'Iris-versicolor']

In [10]:
#coverting the label to numerical label
for i in range(len(trainingclass)):
  for k in range(len(unique_class)):
    if(trainingclass[i]==unique_class[k]):
      trainingclass[i]=k
print(trainingclass)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [42]:
from numpy import random
x = random.choice(len(training), size=(30))
testing=training[x]
testing

array([[4.6, 3.4, 1.4, 0.3],
       [5.5, 4.2, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2.0],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 2.6, 3.5, 1.0],
       [7.7, 2.6, 6.9, 2.3],
       [5.0, 2.3, 3.3, 1.0],
       [6.3, 2.7, 4.9, 1.8],
       [5.7, 2.8, 4.1, 1.3],
       [5.4, 3.7, 1.5, 0.2],
       [6.8, 3.0, 5.5, 2.1],
       [6.1, 2.8, 4.7, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.6, 2.8, 4.9, 2.0],
       [6.7, 3.1, 4.7, 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [5.0, 3.2, 1.2, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.7, 3.0, 5.0, 1.7],
       [7.6, 3.0, 6.6, 2.1],
       [6.1, 2.6, 5.6, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [6.0, 2.9, 4.5, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [7.6, 3.0, 6.6, 2.1],
       [5.2, 4.1, 1.5, 0.1],
       [5.1, 3.5, 1.4, 0.2],
       [4.8, 3.0, 1.4, 0.3],
       [4.9, 2.4, 3.3, 1.0]], dtype=object)

In [46]:
distance=[]
for i in range(len(training)):
  distance.append((euclidean_distance(training[i],testing),trainingclass[i]))

TypeError: ignored

In [ ]:
distance

In [ ]:
distance.sort()
distance

In [15]:
k=5

In [16]:
identify=[0 for i in range(len(unique_class))]

In [17]:
identify

[0, 0, 0]

In [18]:
for i in range(1,k+1):
  identify[distance[i][1]]+=1
print(identify)

[5, 0, 0]


In [ ]:
print("The predicted class is : ",unique_class[identify.index(max(identify))])

The predicted class is :  Iris-setosa


In [28]:
training[0]

array([5.1, 3.5, 1.4, 0.2], dtype=object)

In [34]:
#len(training)
# from sklearn.model_selection import train_test_split
# X_train, X_test,y_train, y_test = train_test_split(training, trainingclass ,random_state=10, test_size=0.25, shuffle=True)

In [30]:
#confusion_matrix(distance,trainingclass)

ValueError: ignored

In [ ]:
#accuracy_score(y_true, y_pred)